// <auto-generated />
using System;
using KParfume.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KParfume.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("KParfumeSchema")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KParfume.Core.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("kor_adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kor_drzava")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kor_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("kor_fab_id")
                        .HasColumnType("bigint");

                    b.Property<string>("kor_grad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kor_ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kor_ime_kompanije")
                        .HasColumnType("text");

                    b.Property<string>("kor_lozinka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kor_pos_br")
                        .HasColumnType("integer");

                    b.Property<string>("kor_prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kor_tel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kor_uloga")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("kor_email")
                        .IsUnique();

                    b.ToTable("Korisnik", "KParfumeSchema");
                });
#pragma warning restore 612, 618
        }
    }
}
